### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by mornhavon** [googlecast/RemoteDisplayUnityPlugin#5]
Thanks @entertailion for your efforts, do you think development will continue in order to bring support to SDK v3 and beyond?

**Comment by Frozenfire92** [comment]
+1 this has a lot of potential but from what I can tell based on my experience and the asset store reviews is it is broken in Unity 5.5+ and not maintained. It would be nice if the code was at least open sourced so someone can try and fix it.

**Comment by entertailion** [comment]
We are working on an update.

**Comment by CarlosHBC** [comment]
Any news?

**Comment by entertailion** [comment]
It has been decided to deprecate the Unity plugin. The Remote Display API will still be supported.

**Comment by Frozenfire92** [comment]
Will you open source it at least?

**Comment by entertailion** [comment]
There are no plans to open source the plugin. The plugin uses the Cast Remote Display API, so you can add that to your Unity projects.
