### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by grrava** [googlecast/RemoteDisplayUnityPlugin#6]
Hello,

I'm currently trying to integrate this plugin into our Unity project.

Everything seems in order, the problem that I have now are these two messages in the log:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbo

This is probably caused by missing libraries in the Assets\Plugins\Android folder, according to your tutorial (https://developers.google.com/cast/docs/remote_unity), but the libraries mentioned in that tutorial do not exist anymore.

I tried selecting other .aar files from the Android SDK, I have now these files in the Assets\Plugins\Android folder:

![image](https://user-images.githubusercontent.com/2426470/34439028-5da6dc8e-ecab-11e7-969a-464676ad5223.png)

However this does not help, although the file play-services-base-11.0.4 seems to contain the correct GoogleApiAvailability class.

What are my options?

Is there any update available of this plugin? Would you be willing to share the source of this plugin? Then I could update it to the latest version...

Thanks for any response,
Alex

**Comment by entertailion** [comment]
This plugin is no longer supported and will not be updated. Their are no plans to make the source code available.
